apiVersion: v1
kind: Service
metadata:
  name: devbook-backend
spec:
  selector:
    app: devbook-backend
    version: blue  # or green, depending on the deployment
  ports:
  - protocol: TCP
    port: 8080
    targetPort: 8080
  type: ClusterIP