apiVersion: apps/v1
kind: Deployment
metadata:
  name: devbook-frontend
spec:
  replicas: 2
  selector:
    matchLabels:
      app: devbook-frontend
  template:
    metadata:
      labels:
        app: devbook-frontend
    spec:
      imagePullSecrets:
      # - name: ghcr-secret
      - name: dockerhub-secret
      restartPolicy: Always
      containers:
      - name: frontend
        # image: ghcr.io/malise5/devbook-frontend:latest
        # image: docker.io/malise/devbook-frontend:latest
        image: docker.io/malise/devbook-frontend:${IMAGE_TAG}
        ports:
        - containerPort: 80
        env:
        - name: VITE_REACT_APP_API_URL
          # value: http://devbook-backend:8080/api/v1/notes
          value: http://devbook.local/api/v1/notes
        
        resources:
          requests:
            memory: "256Mi"
            cpu: "250m"
          limits:
            memory: "512Mi"
            cpu: "500m"
        
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 5
          periodSeconds: 10
        
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 15
          periodSeconds: 20